# Generated by Django 4.2.4 on 2023-08-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('year_of_publication', models.IntegerField()),
                ('publisher', models.CharField(max_length=255)),
                ('image_url_s', models.CharField(max_length=255)),
                ('image_url_m', models.CharField(max_length=255)),
                ('image_url_l', models.CharField(max_length=255)),
            ],
        ),
    ]
